CREATE TABLE IF NOT EXISTS appuser (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS article (
    article_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL CHECK (title <> ''),
    "author_id" INTEGER REFERENCES appuser(user_id)
);

CREATE TABLE IF NOT EXISTS user_follow (
    "user_id" INTEGER REFERENCES appuser(user_id),
    "follows_id" INTEGER REFERENCES appuser(user_id)
);

INSERT INTO appuser(name) VALUES('mike');
INSERT INTO appuser(name) VALUES('jack');
INSERT INTO appuser(name) VALUES('rose');
INSERT INTO appuser(name) VALUES('theo');

INSERT INTO article(title, author_id) VALUES ('what is love', 1);
INSERT INTO article(title, author_id) VALUES ('what is life', 2);
INSERT INTO article(title, author_id) VALUES ('where is the end', 3);

INSERT INTO user_follow(user_id, follows_id) VALUES (1, 2);
INSERT INTO user_follow(user_id, follows_id) VALUES (1, 3);
INSERT INTO user_follow(user_id, follows_id) VALUES (2, 1);
INSERT INTO user_follow(user_id, follows_id) VALUES (3, 4);